// <auto-generated />
using LojaSapatoKhalai.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LojaSapatoKhalai.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LojaSapatoKhalai.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Sapato de luxo"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Chuteiras"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Sapatos casuais"
                        });
                });

            modelBuilder.Entity("LojaSapatoKhalai.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nome")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Sexo")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CPF = "1354532",
                            Endereco = "Mansão maromba",
                            Nome = "Rodrigo",
                            Sexo = "m"
                        },
                        new
                        {
                            Id = 2,
                            CPF = "765432123",
                            Endereco = "Casa do bom filho",
                            Nome = "Marcos",
                            Sexo = "m"
                        },
                        new
                        {
                            Id = 3,
                            CPF = "1354532",
                            Endereco = "Rua Perdida das cruzes",
                            Nome = "Ana",
                            Sexo = "f"
                        });
                });

            modelBuilder.Entity("LojaSapatoKhalai.Models.Estoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdModelo")
                        .HasColumnType("int");

                    b.Property<int>("Qnt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Estoques");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdModelo = 1,
                            Qnt = 1000
                        },
                        new
                        {
                            Id = 2,
                            IdModelo = 2,
                            Qnt = 10
                        },
                        new
                        {
                            Id = 3,
                            IdModelo = 3,
                            Qnt = 110
                        });
                });

            modelBuilder.Entity("LojaSapatoKhalai.Models.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CNPJ")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Fornecedores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CNPJ = "1953049285142",
                            Endereco = "China, shin shon shun",
                            Nome = "China in Shoes"
                        },
                        new
                        {
                            Id = 2,
                            CNPJ = "1276629478241",
                            Endereco = "Africa do Sul, Cidade do Cabo",
                            Nome = "Africa has Shoes"
                        },
                        new
                        {
                            Id = 3,
                            CNPJ = "9994724861245",
                            Endereco = "India, Nova Dehli",
                            Nome = "India doens't do Shoes"
                        });
                });

            modelBuilder.Entity("LojaSapatoKhalai.Models.Modelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodigoRef")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdFornecedor")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<double>("Preco")
                        .HasColumnType("float");

                    b.Property<int>("Tamanho")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Modelos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodigoRef = "asnaeb",
                            Cor = "Branco",
                            IdCategoria = 1,
                            IdFornecedor = 1,
                            Nome = "Supreme Ben 10 mil",
                            Preco = 1500.0,
                            Tamanho = 36
                        },
                        new
                        {
                            Id = 2,
                            CodigoRef = "asnaeba",
                            Cor = "Preto",
                            IdCategoria = 2,
                            IdFornecedor = 2,
                            Nome = "Chute certo",
                            Preco = 350.0,
                            Tamanho = 42
                        },
                        new
                        {
                            Id = 3,
                            CodigoRef = "asnaebbbe",
                            Cor = "Cinza",
                            IdCategoria = 3,
                            IdFornecedor = 3,
                            Nome = "Skatenis",
                            Preco = 150.0,
                            Tamanho = 39
                        });
                });

            modelBuilder.Entity("LojaSapatoKhalai.Models.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DtVenda")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("idCliente")
                        .HasColumnType("int");

                    b.Property<int>("idModelo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vendas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DtVenda = "22/06/2021",
                            Quantidade = 10,
                            idCliente = 1,
                            idModelo = 1
                        },
                        new
                        {
                            Id = 2,
                            DtVenda = "19/10/2021",
                            Quantidade = 1,
                            idCliente = 2,
                            idModelo = 2
                        },
                        new
                        {
                            Id = 3,
                            DtVenda = "03/11/2021",
                            Quantidade = 1,
                            idCliente = 3,
                            idModelo = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
